apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-debit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-worker-debit.k8"
  API_VERSION: "2.1"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "SASL_SSL"
  KAFKA_MECHANISM: "SCRAM-SHA-512"
  KAFKA_CLIENT_ID: "GO-WORKER-DEBIT"
  KAFKA_GROUP_ID: "GROUP-GO-WORKER-DEBIT-01"
  KAFKA_BROKER_1: "b-1.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_2: "b-2.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_3: "b-3.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "2"
  TOPIC_DEBIT: "topic.debit.01"
  SERVICE_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "7egms7zn67"

  #SERVICE_URL_DOMAIN: "http://svc-go-debit.test-a.svc.cluster.local:5002"