apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-debit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-worker-debit"
  API_VERSION: "1.0"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  NO_AZ: "true"
  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "PLAINTEXT"
  KAFKA_MECHANISM: "PLAINTEXT"
  KAFKA_CLIENT_ID: "GO-WORKER-BALANCE"
  KAFKA_GROUP_ID: "GROUP-03"
  KAFKA_BROKER_1: "b-1.mskarchtest02.9vkh4b.c3.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_2: "b-2.mskarchtest02.9vkh4b.c3.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_3: ""
  KAFKA_PARTITION: "1"
  KAFKA_REPLICATION: "1"