apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-balance-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-worker-balance"
  API_VERSION: "1.0"
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "PLAINTEXT"
  KAFKA_MECHANISM: "PLAINTEXT"
  KAFKA_CLIENT_ID: "GO-WORKER-DEBIT"
  KAFKA_GROUP_ID: "GROUP-GO-WORKER-DEBIT-01"
  KAFKA_BROKER_1: "b-1.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_2: "b-2.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_3: "b-3.mskarchtest03.p70t1p.c6.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "2"
  TOPICS: "topic.debit.01"
  #SERVICE_URL_DOMAIN: "http://svc-go-debit.test-a.svc.cluster.local:5002"
  SERVICE_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "7egms7zn67"